### ISSUE TITLE
can you add a simple github actions?

### ISSUE THREAD

**Issue by LecrisUT** [dialecticDolt/skbuild-core-import#1]
Also would be helpful to see the last line in the _editable.py file

**Comment by dialecticDolt** [comment]
For the moment I set up some (very) minimal actions to just compare the editable and non-editable installs on `main` and in `nocython`.

Which "_editable.py" file do you mean?

**Comment by LecrisUT** [comment]
Thank you. I will try to reproduce it in the scikit-build-core tests.
